### ISSUE TITLE
Filtered bundles endpoint returns IDs of deleted bundles

### ISSUE THREAD

**Issue by teschmitt** [dtn7/dtn7-rs#40]
IDs of deleted bundles are *not* returned when querying the `/status/bundles` endpoint, but are returned when they match a query to the `/status/bundles/filtered` endpoint:
```shell
$ curl http://127.0.0.1:3000/status/bundles
[]

$ curl http://127.0.0.1:3000/status/bundles/filtered\?addr\=abcdefg
[
  "dtn://n1/mail/abcdefg-717328651177-0",
  "dtn://n1/mail/abcdefg-717329554776-0",
  "dtn://n1/mail/abcdefg-717329333204-0",
  "dtn://n1/mail/abcdefg-717329397442-0"
]
```
This behavior is inconsistent and easily leads to errors, since deleted bundle IDs are shown just like IDs of stored and hence downloadable bundles.

**Comment by gh0st42** [comment]
Good find! This is counterintuitive and should be fixed.

Thanks for reporting the issue!

**Comment by gh0st42** [comment]
the issue should be fixed now
